import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:file_picker/file_picker.dart';

void main() {
  runApp(const FileManagerApp());
  }

  class FileManagerApp extends StatelessWidget {
    const FileManagerApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  title: 'Dosya Yöneticisi',
                        theme: ThemeData(
                                colorSchemeSeed: Colors.indigo,
                                        useMaterial3: true,
                                              ),
                                                    home: const FileExplorer(),
                                                        );
                                                          }
                                                          }

                                                          class FileExplorer extends StatefulWidget {
                                                            const FileExplorer({super.key});

                                                              @override
                                                                State<FileExplorer> createState() => _FileExplorerState();
                                                                }

                                                                class _FileExplorerState extends State<FileExplorer> {
                                                                  Directory? currentDir;
                                                                    List<FileSystemEntity> files = [];

                                                                      @override
                                                                        void initState() {
                                                                            super.initState();
                                                                                _init();
                                                                                  }

                                                                                    Future<void> _init() async {
                                                                                        await Permission.storage.request();
                                                                                            Directory dir = Directory('/storage/emulated/0');
                                                                                                _openDirectory(dir);
                                                                                                  }

                                                                                                    void _openDirectory(Directory dir) {
                                                                                                        setState(() {
                                                                                                              currentDir = dir;
                                                                                                                    files = dir.listSync();
                                                                                                                        });
                                                                                                                          }

                                                                                                                            Future<void> _deleteEntity(FileSystemEntity entity) async {
                                                                                                                                await entity.delete(recursive: true);
                                                                                                                                    _openDirectory(currentDir!);
                                                                                                                                      }

                                                                                                                                        Future<void> _renameEntity(FileSystemEntity entity) async {
                                                                                                                                            TextEditingController controller =
                                                                                                                                                    TextEditingController(text: entity.uri.pathSegments.last);
                                                                                                                                                        String? newName = await showDialog<String>(
                                                                                                                                                              context: context,
                                                                                                                                                                    builder: (context) => AlertDialog(
                                                                                                                                                                            title: const Text("Yeniden Adlandır"),
                                                                                                                                                                                    content: TextField(controller: controller),
                                                                                                                                                                                            actions: [
                                                                                                                                                                                                      TextButton(
                                                                                                                                                                                                                    onPressed: () => Navigator.pop(context),
                                                                                                                                                                                                                                  child: const Text("İptal")),
                                                                                                                                                                                                                                            TextButton(
                                                                                                                                                                                                                                                          onPressed: () => Navigator.pop(context, controller.text),
                                                                                                                                                                                                                                                                        child: const Text("Kaydet")),
                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                              if (newName != null && newName.isNotEmpty) {
                                                                                                                                                                                                                                                                                                    String newPath = "${entity.parent.path}/$newName";
                                                                                                                                                                                                                                                                                                          await entity.rename(newPath);
                                                                                                                                                                                                                                                                                                                _openDirectory(currentDir!);
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                        Future<void> _copyEntity(FileSystemEntity entity) async {
                                                                                                                                                                                                                                                                                                                            if (entity is File) {
                                                                                                                                                                                                                                                                                                                                  final destPath = "${currentDir!.path}/${entity.uri.pathSegments.last}";
                                                                                                                                                                                                                                                                                                                                        await entity.copy(destPath);
                                                                                                                                                                                                                                                                                                                                              _openDirectory(currentDir!);
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                      void _goBack() {
                                                                                                                                                                                                                                                                                                                                                          if (currentDir?.parent.path != currentDir?.path) {
                                                                                                                                                                                                                                                                                                                                                                _openDirectory(currentDir!.parent);
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                                                                                          Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                              return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                    appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                            title: Text(currentDir?.path ?? "Dosya Yöneticisi"),
                                                                                                                                                                                                                                                                                                                                                                                                    leading: IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                              icon: const Icon(Icons.arrow_back),
                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: _goBack,
                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                        actions: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                  IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon: const Icon(Icons.add),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        String? result = await FilePicker.platform.getDirectoryPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (result != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      _openDirectory(Directory(result));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              body: ListView.builder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      itemCount: files.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        final entity = files[index];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  final isDir = FileSystemEntity.isDirectorySync(entity.path);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        leading: Icon(isDir ? Icons.folder : Icons.insert_drive_file),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: Text(entity.uri.pathSegments.last),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onTap: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (isDir) _openDirectory(Directory(entity.path));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      trailing: PopupMenuButton<String>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onSelected: (value) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    switch (value) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case 'delete':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          _deleteEntity(entity);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 'rename':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _renameEntity(entity);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case 'copy':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _copyEntity(entity);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              itemBuilder: (context) => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const PopupMenuItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value: 'rename', child: Text('Yeniden Adlandır')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const PopupMenuItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value: 'copy', child: Text('Kopyala')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const PopupMenuItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value: 'delete', child: Text('Sil')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }